import { create } from 'zustand';

type Language = 'en' | 'ar';

interface LanguageState {
  lang: Language;
  dir: 'ltr' | 'rtl';
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<string, Record<string, string>> = {
  en: {
    // Brand
    'brand.full': 'Al Mahata Al Wahedah',
    'brand.short': 'Al Mahata',
    'brand.ar': 'المحطة الوحيدة',
    'brand.tagline': 'The Only Station — Auto Maintenance',
    'brand.location': 'Sharjah',

    // Nav
    'nav.home': 'Home',
    'nav.services': 'Services',
    'nav.about': 'About',
    'nav.promotions': 'Offers',
    'nav.gallery': 'Gallery',
    'nav.faq': 'FAQ',
    'nav.contact': 'Contact',
    'nav.book': 'Book Now',
    'nav.lang': 'عربي',

    // Hero
    'hero.tagline': 'PREMIUM CAR GARAGE IN SHARJAH',
    'hero.title': 'Expert Auto Repair for Every Car',
    'hero.subtitle': 'From engine overhauls to bodywork perfection — we service GCC, US, German, and Asian vehicles with certified precision. Your one-stop solution for all automotive needs.',
    'hero.cta.book': 'Book Appointment',
    'hero.cta.call': 'Call Now',
    'hero.cta.recovery': '24/7 Recovery Service',

    // Services (11 total)
    'services.tagline': 'WHAT WE DO',
    'services.title': 'Complete Auto Care Solutions',
    'services.subtitle': 'From routine maintenance to complex repairs, our certified technicians handle every aspect of your vehicle with expertise and care.',
    'services.engine.title': 'Engine Repair',
    'services.engine.desc': 'Complete engine diagnostics, rebuilds, and performance tuning for all vehicle types. We handle everything from minor fixes to full engine overhauls.',
    'services.mechanical.title': 'Mechanical Repair',
    'services.mechanical.desc': 'Transmission, brakes, clutch, steering, and all mechanical components. Precision repairs using genuine and quality aftermarket parts.',
    'services.electrical.title': 'Electrical Systems',
    'services.electrical.desc': 'Advanced electrical diagnostics, wiring repairs, ECU programming, sensor replacements, and complete electrical system overhauls.',
    'services.suspension.title': 'Suspension & Steering',
    'services.suspension.desc': 'Shock absorbers, coil springs, control arms, wheel alignment, and balancing. Restore your ride comfort and handling precision.',
    'services.body.title': 'Body Work & Paint',
    'services.body.desc': 'Professional denting, painting, panel beating, and full body restoration. Factory-quality finish with color-matching technology.',
    'services.recovery.title': 'Recovery & Towing',
    'services.recovery.desc': '24/7 emergency towing and vehicle recovery across all UAE. Fast response, flatbed carriers, and safe transport for any vehicle.',
    'services.ac.title': 'AC & Cooling',
    'services.ac.desc': 'Complete AC system service including gas refill, compressor repair, condenser cleaning, and climate control diagnostics.',
    'services.oil.title': 'Oil Change',
    'services.oil.desc': 'Premium semi-synthetic and fully synthetic oil changes as per manufacturer specs. Includes filter replacement and fluid top-up.',
    'services.brakes.title': 'Brake Pads & Rotors',
    'services.brakes.desc': 'Brake pad replacement, rotor resurfacing, brake fluid flush, and full brake system inspection for optimal stopping power.',
    'services.battery.title': 'Battery Replacement',
    'services.battery.desc': 'Battery testing, replacement, and charging system diagnostics. We stock batteries for all major brands with warranty coverage.',
    'services.transmission.title': 'Transmission & Gearbox',
    'services.transmission.desc': 'Complete transmission diagnostics, fluid change, rebuild, and replacement. Expert care for automatic and manual gearboxes.',
    'services.viewall': 'View Details',

    // About
    'about.tagline': 'WHO WE ARE',
    'about.title': 'Trusted by Sharjah Car Owners',
    'about.desc': 'With years of experience serving Sharjah\'s diverse automotive market, we\'ve built our reputation on honesty, quality, and reliability. Our team of certified technicians specializes in GCC-spec, US-import, German, and Asian vehicles — ensuring every car receives the expert care it deserves.',
    'about.stat1.num': '1,500+',
    'about.stat1.label': 'Cars Serviced',
    'about.stat2.num': '3+',
    'about.stat2.label': 'Years Experience',
    'about.stat3.num': '10+',
    'about.stat3.label': 'Expert Technicians',
    'about.stat4.num': '99%',
    'about.stat4.label': 'Customer Satisfaction',

    // Why Choose Us
    'why.tagline': 'WHY CHOOSE US',
    'why.title': 'The Al Mahata Al Wahedah Difference',
    'why.247.title': '24/7 Recovery Service',
    'why.247.desc': 'Round-the-clock emergency towing and recovery across Sharjah. We\'re always there when you need us most.',
    'why.free.title': 'Free Inspection',
    'why.free.desc': 'Complimentary vehicle diagnostic and inspection for first-time customers. Know exactly what your car needs before you pay.',
    'why.warranty.title': 'Repair Warranty',
    'why.warranty.desc': 'All our repairs come with a service warranty. If something isn\'t right, we\'ll fix it at no extra cost.',
    'why.brands.title': 'All Car Brands',
    'why.brands.desc': 'We service GCC-spec, US-import, German luxury, and Asian vehicles. No matter what you drive, we can fix it.',
    'why.transparent.title': 'Transparent Pricing',
    'why.transparent.desc': 'No hidden fees or surprise charges. You get a detailed quote before any work begins, every single time.',
    'why.genuine.title': 'Quality Parts',
    'why.genuine.desc': 'We use genuine OEM parts and trusted aftermarket brands to ensure lasting quality and performance.',

    // Trust Badges
    'trust.tagline': 'OUR PROMISE',
    'trust.title': '100% Result Guarantee',
    'trust.subtitle': 'Your satisfaction is our first priority. We stand behind every repair with our guarantee.',
    'trust.fair.title': 'Fair-Price Service',
    'trust.fair.desc': 'Competitive pricing with no hidden costs. Get the best value for quality auto care in Sharjah.',
    'trust.certified.title': 'High Quality Certified',
    'trust.certified.desc': 'Our technicians are certified professionals using state-of-the-art diagnostic equipment and genuine parts.',
    'trust.guarantee.title': '100% Satisfaction Guarantee',
    'trust.guarantee.desc': 'Not happy with the result? We\'ll make it right at no extra charge. That\'s our promise to every customer.',

    // Promotions
    'promo.tagline': 'SPECIAL OFFERS',
    'promo.title': 'Save on Your Next Service',
    'promo.subtitle': 'Take advantage of our exclusive promotions and keep your car running at its best without breaking the bank.',
    'promo.first.title': 'First Service 20% Off',
    'promo.first.desc': 'New to Al Mahata Al Wahedah? Get 20% off your first service. Valid for all repair and maintenance work.',
    'promo.first.cta': 'Claim Offer',
    'promo.freeInspection.title': 'Free Diagnostic',
    'promo.freeInspection.desc': 'Not sure what\'s wrong? Get a complete vehicle diagnostic absolutely free — no strings attached.',
    'promo.freeInspection.cta': 'Book Free Check',
    'promo.ac.title': 'AC Service AED 149',
    'promo.ac.desc': 'Full AC system check, gas top-up, and performance test for just AED 149. Beat the Sharjah heat!',
    'promo.ac.cta': 'Book AC Service',
    'promo.recovery.title': 'Recovery 15% Off',
    'promo.recovery.desc': 'Flat 15% discount on all towing and recovery services across Sharjah. Available 24/7.',
    'promo.recovery.cta': 'Save Now',
    'promo.referral.title': 'Refer & Earn',
    'promo.referral.desc': 'Refer a friend and both of you get AED 100 credit toward your next service.',
    'promo.referral.cta': 'Refer a Friend',
    'promo.seasonal.title': 'Summer Special',
    'promo.seasonal.desc': 'Complete summer check-up package: battery, AC, coolant, tires, and brakes — all in one visit.',
    'promo.seasonal.cta': 'Get Package',

    // Testimonials
    'testimonials.tagline': 'TESTIMONIALS',
    'testimonials.title': 'What Our Customers Say',
    'testimonials.1.name': 'Ahmed Al Maktoum',
    'testimonials.1.car': 'Toyota Land Cruiser — GCC Spec',
    'testimonials.1.text': 'Best garage in Sharjah, hands down. They diagnosed an engine issue that two other shops couldn\'t figure out. Fair pricing and honest team. Highly recommend!',
    'testimonials.2.name': 'Sarah Johnson',
    'testimonials.2.car': 'BMW X5 — US Import',
    'testimonials.2.text': 'Finally found a garage that properly handles my US-spec BMW. The electrical work was flawless and the AC is running like new. Will definitely come back.',
    'testimonials.3.name': 'Mohammed Khan',
    'testimonials.3.car': 'Mercedes C-Class',
    'testimonials.3.text': 'Used their recovery service at 2 AM after a breakdown. They arrived in 25 minutes and towed my car safely. Professional and reliable!',
    'testimonials.4.name': 'James Wilson',
    'testimonials.4.car': 'Nissan Patrol — GCC Spec',
    'testimonials.4.text': 'The bodywork on my Patrol after an accident was absolutely perfect. You can\'t even tell it was damaged. Outstanding paint matching and attention to detail.',
    'testimonials.5.name': 'Fatima Al Hashmi',
    'testimonials.5.car': 'Lexus RX 350',
    'testimonials.5.text': 'Transparent pricing, great communication, and quality work. They sent me photos of the repair process via WhatsApp. This is how every garage should operate.',
    'testimonials.6.name': 'Raj Patel',
    'testimonials.6.car': 'Honda Civic',
    'testimonials.6.text': 'Brought my Civic for suspension work. The difference in ride quality is night and day. They also found a worn bushing I didn\'t know about and fixed it without extra charge.',

    // Gallery
    'gallery.tagline': 'OUR WORK',
    'gallery.title': 'Recent Projects',
    'gallery.subtitle': 'A showcase of our craftsmanship — from precision engine rebuilds to flawless bodywork and paint restorations.',
    'gallery.coming': 'Photos coming soon — we\'re curating our best work for you!',

    // FAQ
    'faq.tagline': 'FAQ',
    'faq.title': 'Frequently Asked Questions',
    'faq.1.q': 'What car brands do you service?',
    'faq.1.a': 'We service all car brands including Toyota, Nissan, Honda, BMW, Mercedes-Benz, Audi, Porsche, Lexus, Ford, Chevrolet, Hyundai, Kia, and many more. We specialize in GCC-spec, US-import, German, and Asian vehicles.',
    'faq.2.q': 'Do you offer a warranty on repairs?',
    'faq.2.a': 'Yes! All our repairs come with a service warranty. The warranty period depends on the type of repair and parts used. We stand behind our work and will fix any issues at no extra cost within the warranty period.',
    'faq.3.q': 'How quickly can you respond for recovery/towing?',
    'faq.3.a': 'Our average response time is 20-30 minutes anywhere in Sharjah. We operate 24/7, 365 days a year, with a fleet of flatbed carriers and experienced drivers to safely transport your vehicle.',
    'faq.4.q': 'Do you provide free vehicle inspection?',
    'faq.4.a': 'Yes, we offer a complimentary diagnostic and inspection for first-time customers. This includes a comprehensive check of engine, brakes, suspension, electrical systems, and fluid levels — completely free of charge.',
    'faq.5.q': 'Can I get a quote before any work begins?',
    'faq.5.a': 'Absolutely. We provide detailed written quotes before starting any work. There are no hidden fees or surprise charges. You approve the quote, and we proceed only with your go-ahead.',
    'faq.6.q': 'What are your payment methods?',
    'faq.6.a': 'We accept cash, all major credit/debit cards, bank transfer, and Apple Pay. For larger repair jobs, we also offer flexible payment plans. Insurance claims for accident repairs are also handled.',
    'faq.7.q': 'Do you use genuine parts?',
    'faq.7.a': 'We use genuine OEM parts wherever possible. When OEM parts are not available, we use trusted aftermarket brands that meet or exceed original specifications. We always discuss part options and pricing with you beforehand.',
    'faq.8.q': 'How do I book an appointment?',
    'faq.8.a': 'You can book an appointment through our website, call us directly, send a WhatsApp message, or simply walk in during business hours. For emergency recovery, call our 24/7 hotline anytime.',

    // Contact
    'contact.tagline': 'GET IN TOUCH',
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Have a question or need to book a service? Reach out to us through any of the channels below.',
    'contact.form.name': 'Full Name',
    'contact.form.email': 'Email Address',
    'contact.form.phone': 'Phone Number',
    'contact.form.service': 'Service Required',
    'contact.form.service.placeholder': 'Select a service',
    'contact.form.message': 'Message',
    'contact.form.message.placeholder': 'Tell us about your vehicle and the issue...',
    'contact.form.submit': 'Send Message',
    'contact.form.success': 'Message sent successfully! We\'ll get back to you soon.',
    'contact.info.title': 'Quick Contact',
    'contact.info.address': '8JPR+J2M - Al Sajaa - Emirates Industrial City - Sharjah - United Arab Emirates',
    'contact.info.hours': 'Sat–Thu: 8:00 AM – 9:00 PM',
    'contact.info.hours.friday': 'Friday: 2:00 PM – 9:00 PM',
    'contact.info.hours.recovery': 'Recovery: 24/7',
    'contact.info.follow': 'Follow Us',

    // Booking
    'booking.title': 'Book an Appointment',
    'booking.name': 'Your Name',
    'booking.phone': 'Phone Number',
    'booking.email': 'Email',
    'booking.car': 'Car Make & Model',
    'booking.car.placeholder': 'e.g., Toyota Land Cruiser 2023',
    'booking.service': 'Service Type',
    'booking.service.placeholder': 'Select service',
    'booking.date': 'Preferred Date',
    'booking.time': 'Preferred Time',
    'booking.time.placeholder': 'Select time',
    'booking.notes': 'Additional Notes',
    'booking.notes.placeholder': 'Describe the issue or service needed...',
    'booking.submit': 'Confirm Booking',
    'booking.success': 'Booking confirmed! We\'ll contact you shortly to confirm.',

    // Footer
    'footer.desc': 'Sharjah\'s trusted full-service car garage. Expert repairs for GCC, US, German, and Asian vehicles. Quality work, transparent pricing, and 24/7 recovery service.',
    'footer.quicklinks': 'Quick Links',
    'footer.services': 'Services',
    'footer.contact': 'Contact',
    'footer.rights': 'All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
  },
  ar: {
    // Brand
    'brand.full': 'المحطة الوحيدة',
    'brand.short': 'المحطة',
    'brand.ar': 'المحطة الوحيدة',
    'brand.tagline': 'المحطة الوحيدة — صيانة سيارات',
    'brand.location': 'الشارقة',

    // Nav
    'nav.home': 'الرئيسية',
    'nav.services': 'الخدمات',
    'nav.about': 'من نحن',
    'nav.promotions': 'العروض',
    'nav.gallery': 'أعمالنا',
    'nav.faq': 'الأسئلة الشائعة',
    'nav.contact': 'اتصل بنا',
    'nav.book': 'حجز موعد',
    'nav.lang': 'EN',

    // Hero
    'hero.tagline': 'ورشة سيارات مميزة في الشارقة',
    'hero.title': 'إصلاح احترافي لكل السيارات',
    'hero.subtitle': 'من إعادة بناء المحركات إلى إصلاح الهيكل بالكمال — نخدم سيارات الخليج والولايات المتحدة والألمانية والآسيوية بدقة معتمدة. حلكم الشامل لجميع احتياجات سيارتك.',
    'hero.cta.book': 'حجز موعد',
    'hero.cta.call': 'اتصل بنا',
    'hero.cta.recovery': 'خدمة استعادة 24/7',

    // Services (11 total)
    'services.tagline': 'ما نقدمه',
    'services.title': 'حلول صيانة سيارات شاملة',
    'services.subtitle': 'من الصيانة الدورية إلى الإصلاحات المعقدة، يتعامل فنيونا المعتمدون مع كل جانب من سيارتك بخبرة وعناية.',
    'services.engine.title': 'إصلاح المحركات',
    'services.engine.desc': 'تشخيص شامل للمحركات وإعادة بناء وضبط الأداء لجميع أنواع المركبات. نتعامل مع كل شيء من الإصلاحات البسيطة إلى إعادة بناء المحرك بالكامل.',
    'services.mechanical.title': 'إصلاح ميكانيكي',
    'services.mechanical.desc': 'نقل الحركة والفرامل والقبضة والتوجيه وجميع الأجزاء الميكانيكية. إصلاحات دقيقة باستخدام قطع أصلية ومعتمدة.',
    'services.electrical.title': 'الأنظمة الكهربائية',
    'services.electrical.desc': 'تشخيص كهربائي متقدم وإصلاح التمديدات وبرمجة الكمبيوتر واستبدال المجسات وإصلاح شامل للنظام الكهربائي.',
    'services.suspension.title': 'المقاصات والتوجيه',
    'services.suspension.desc': 'مصادمات الصدم ونوابض الحلق وذراع التحكم ومحاذاة العجلات وتوازنها. استعد راحة القيادة ودقة التوجيه.',
    'services.body.title': 'الهيكل والدهان',
    'services.body.desc': 'إصلاح النقر والدهان الاحترافي وإعادة ترميم الهيكل بجودة المصنع مع تطبيق الألوان.',
    'services.recovery.title': 'استعادة وسحب',
    'services.recovery.desc': 'خدمة سحب واستعادة طوارئ على مدار الساعة في جميع أنحاء الإمارات العربية المتحدة. استجابة سريعة ونقل آمن لأي مركبة.',
    'services.ac.title': 'التكييف والتبريد',
    'services.ac.desc': 'خدمة شاملة لنظام التكييف تشمل إعادة تعبئة الغاز وإصلاح الضاغط وتنظيف المكثف.',
    'services.oil.title': 'تغيير الزيت',
    'services.oil.desc': 'تغيير زيت شبه مصنوع ومصنوع بالكامل حسب مواصفات الشركة المصنعة. يشمل تغيير الفلتر وتعبئة السوائل.',
    'services.brakes.title': 'أقراص الفرامل',
    'services.brakes.desc': 'استبدال تيلات الفرامل وتسوية الأقراص وتغيير زيت الفرامل وفحص شامل لنظام الفرامل.',
    'services.battery.title': 'استبدال البطارية',
    'services.battery.desc': 'فحص البطارية والاستبدال وتشخيص نظام الشحن. نوفر بطاريات لجميع الماركات مع ضمان.',
    'services.transmission.title': 'نقل الحركة والصندوق',
    'services.transmission.desc': 'تشخيص شامل لناقل الحركة وتغيير الزيت والإعادة بناء والاستبدال. عناية خبيرة للنواقل الأوتوماتيكية واليدوية.',
    'services.viewall': 'عرض التفاصيل',

    // About
    'about.tagline': 'من نحن',
    'about.title': 'ثقة أصحاب السيارات في الشارقة',
    'about.desc': 'مع سنوات من الخبرة في خدمة سوق السيارات المتنوع في الشارقة، بنينا سمعتنا على الصدق والجودة والموثوقية. فريقنا من الفنيين المعتمدين متخصصون في السيارات الخليجية والأمريكية والألمانية والآسيوية.',
    'about.stat1.num': '+1,500',
    'about.stat1.label': 'سيارة تم خدمتها',
    'about.stat2.num': '+3',
    'about.stat2.label': 'سنوات خبرة',
    'about.stat3.num': '+10',
    'about.stat3.label': 'فني متخصص',
    'about.stat4.num': '99%',
    'about.stat4.label': 'رضا العملاء',

    // Why Choose Us
    'why.tagline': 'لماذا نحن',
    'why.title': 'ما يميز المحطة الوحيدة',
    'why.247.title': 'خدمة استعادة 24/7',
    'why.247.desc': 'سحب واستعادة طوارئ على مدار الساعة في جميع أنحاء الشارقة. نحن دائماً موجودون عندما تحتاجنا.',
    'why.free.title': 'فحص مجاني',
    'why.free.desc': 'تشخيص مجاني للسيارة للعملاء الجدد. اعرف بالضبط ما تحتاجه سيارتك قبل الدفع.',
    'why.warranty.title': 'ضمان الإصلاح',
    'why.warranty.desc': 'جميع إصلاحاتنا مع ضمان الخدمة. إذا كان هناك أي مشكلة، سنقوم بإصلاحها مجاناً.',
    'why.brands.title': 'جميع الماركات',
    'why.brands.desc': 'نخدم السيارات الخليجية والأمريكية والألمانية الفاخرة والآسيوية. لا يهم ما تقوده، نستطيع إصلاحه.',
    'why.transparent.title': 'أسعار شفافة',
    'why.transparent.desc': 'لا تكاليف مخفية. تحصل على عرض سعر مفصل قبل بداية أي عمل.',
    'why.genuine.title': 'قطع أصلية',
    'why.genuine.desc': 'نستخدم قطعاً أصلية OEM وماركات موثوقة لضمان جودة دائمة وأداء ممتاز.',

    // Trust Badges
    'trust.tagline': 'وعدنا لكم',
    'trust.title': 'ضمان النتيجة 100%',
    'trust.subtitle': 'رضاكم هو أولويتنا الأولى. نقف وراء كل إصلاح بضماننا.',
    'trust.fair.title': 'أسعار عادلة',
    'trust.fair.desc': 'أسعار تنافسية بدون تكاليف مخفية. أفضل قيمة لصيانة سيارات احترافية في الشارقة.',
    'trust.certified.title': 'جودة معتمدة',
    'trust.certified.desc': 'فنيونا معتمدون محترفون يستخدمون أحدث معدات التشخيص وقطع غيار أصلية.',
    'trust.guarantee.title': 'ضمان رضا العميل 100%',
    'trust.guarantee.desc': 'غير راضٍ عن النتيجة؟ سنصلحها بدون تكلفة إضافية. هذا وعدنا لكل عميل.',

    // Promotions
    'promo.tagline': 'عروض خاصة',
    'promo.title': 'وفر في خدمتك القادمة',
    'promo.subtitle': 'استفد من عروضنا الحصرية وحافظ على سيارتك بأفضل حالة.',
    'promo.first.title': 'خصم 20% على أول خدمة',
    'promo.first.desc': 'عميل جديد؟ احصل على خصم 20% على أول خدمة. ينطبق على جميع أعمال الإصلاح والصيانة.',
    'promo.first.cta': 'احصل على العرض',
    'promo.freeInspection.title': 'تشخيص مجاني',
    'promo.freeInspection.desc': 'لست متأكدًا من المشكلة؟ احصل على تشخيص شامل مجاناً بدون أي التزامات.',
    'promo.freeInspection.cta': 'حجز فحص مجاني',
    'promo.ac.title': 'خدمة التكييف 149 درهم',
    'promo.ac.desc': 'فحص شامل لنظام التكييف وتعبئة الغاز بفقط 149 درهم. تحمل حرارة الشارقة!',
    'promo.ac.cta': 'حجز خدمة التكييف',
    'promo.recovery.title': 'خصم 15% على الاستعادة',
    'promo.recovery.desc': 'خصم 15% على جميع خدمات السحب والاستعادة في الشارقة. متاح على مدار الساعة.',
    'promo.recovery.cta': 'احصل على الخصم',
    'promo.referral.title': 'أحل واربح',
    'promo.referral.desc': 'أحل صديق واحصل كلاكما على 100 درهم رصيد لخدمتك القادمة.',
    'promo.referral.cta': 'أحل صديق',
    'promo.seasonal.title': 'عرض الصيف',
    'promo.seasonal.desc': 'باقة فحص شاملة: البطارية والتكييف والمبرد والإطارات والفرامل — كلها في زيارة واحدة.',
    'promo.seasonal.cta': 'احصل على الباقة',

    // Testimonials
    'testimonials.tagline': 'آراء العملاء',
    'testimonials.title': 'ماذا يقول عملاؤنا',
    'testimonials.1.name': 'أحمد آل مكتوم',
    'testimonials.1.car': 'تويوتا لاند كرويزر — مواصفات خليجية',
    'testimonials.1.text': 'أفضل ورشة في الشارقة بلا منافسة. شخصوا مشكلة في المحرك لم تستطع ورشتان أخريان حلها. أسعار عادلة وفريق صادق. أنصح بشدة!',
    'testimonials.2.name': 'سارة جونسون',
    'testimonials.2.car': 'BMW X5 — واردة أمريكية',
    'testimonials.2.text': 'أخيراً وجدت ورشة تتعامل مع BMW الأمريكية بشكل صحيح. العمل الكهربائي كان مثالياً والتكييف يعمل كالجديد.',
    'testimonials.3.name': 'محمد خان',
    'testimonials.3.car': 'مرسيديس سي كلاس',
    'testimonials.3.text': 'استخدمت خدمة الاستعادة الساعة 2 صباحاً بعد عطل. وصلوا خلال 25 دقيقة ونقلوا سيارتي بأمان. محترفون وموثوقون!',
    'testimonials.4.name': 'جيمس ويلسون',
    'testimonials.4.car': 'نيسان باترول — مواصفات خليجية',
    'testimonials.4.text': 'عمل الهيكل على باترول بعد حادث كان مثالياً. لا يمكنك معرفة أنها تعرضت لأي ضرر. تطبيق الألوان مذهل والاهتمام بالتفاصيل رائع.',
    'testimonials.5.name': 'فاطمة الهاشمي',
    'testimonials.5.car': 'لكزس RX 350',
    'testimonials.5.text': 'أسعار شفافة وتواصل ممتاز وعمل بجودة عالية. أرسلوا لي صور الإصلاح عبر واتساب. هكذا يجب أن تعمل كل ورشة.',
    'testimonials.6.name': 'راج باتل',
    'testimonials.6.car': 'هوندا سيفيك',
    'testimonials.6.text': 'جلبت سيفيكي لإصلاح المقاصات. الفرق في راحة القيادة كبير جداً. وجدوا كوشنك متآكل وأصلحوه بدون تكلفة إضافية.',

    // Gallery
    'gallery.tagline': 'أعمالنا',
    'gallery.title': 'مشاريع حديثة',
    'gallery.subtitle': 'معرض لحرفيتنا — من إعادة بناء المحركات إلى إصلاح الهيكل والدهان بالكمال.',
    'gallery.coming': 'صور قريباً — نعد تحضير أفضل أعمالنا لكم!',

    // FAQ
    'faq.tagline': 'أسئلة شائعة',
    'faq.title': 'الأسئلة الأكثر شيوعاً',
    'faq.1.q': 'ما هي ماركات السيارات التي تخدمونها؟',
    'faq.1.a': 'نخدم جميع الماركات بما في ذلك تويوتا ونيسان وهوندا وBMW ومرسيديس وأودي وبورشه ولكزس وفورد وشيفروليه وهيونداي وكيا وغيرها. نتخصص في السيارات الخليجية والأمريكية والألمانية والآسيوية.',
    'faq.2.q': 'هل تقدمون ضماناً على الإصلاحات؟',
    'faq.2.a': 'نعم! جميع إصلاحاتنا مع ضمان خدمة. فترة الضمان تختلف حسب نوع الإصلاح والقطع المستخدمة. نقف وراء عملنا وسنقوم بإصلاح أي مشكلة مجاناً.',
    'faq.3.q': 'كم سريعاً يمكنكم الاستجابة لخدمة الاستعادة؟',
    'faq.3.a': 'وقت الاستجابة المتوسط هو 20-30 دقيقة في أي مكان في الشارقة. نعمل 24/7، 365 يوماً في السنة.',
    'faq.4.q': 'هل تقدمون فحص مجاني للسيارة؟',
    'faq.4.a': 'نعم، نقدم تشخيصاً وفحصاً مجانياً للعملاء الجدد. يشمل فحصاً شاملاً للمحرك والفرامل والمقاصات والأنظمة الكهربائية ومستويات السوائل مجاناً تماماً.',
    'faq.5.q': 'هل يمكنني الحصول على عرض سعر قبل بداية العمل؟',
    'faq.5.a': 'بالتأكيد. نقدم عروض أسعار مكتوبة ومفصلة قبل بداية أي عمل. لا تكاليف مخفية.',
    'faq.6.q': 'ما هي طرق الدفع المتاحة؟',
    'faq.6.a': 'نقبل الكشف وجميع بطاقات الائتمان والحوالة البنكية وApple Pay. للإصلاحات الكبيرة، نقدم أيضاً خطط دفع مرنة.',
    'faq.7.q': 'هل تستخدمون قطعاً أصلية؟',
    'faq.7.a': 'نستخدم قطعاً أصلية OEM حيثما أمكن. عندما لا تكون القطع الأصلية متاحة، نستخدم ماركات موثوقة تلبي المواصفات الأصلية أو تتجاوزها.',
    'faq.8.q': 'كيف أحجز موعداً؟',
    'faq.8.a': 'يمكنك حجز موعد من خلال موقعنا أو الاتصال بنا مباشرة أو إرسال رسالة واتساب أو القدوم مباشرة خلال ساعات العمل. لخدمة الاستعادة الطارئة، اتصل بخطنا على مدار الساعة.',

    // Contact
    'contact.tagline': 'تواصل معنا',
    'contact.title': 'اتصل بنا',
    'contact.subtitle': 'هل لديك سؤال أو تحتاج لحجز خدمة؟ تواصل معنا من خلال أي من القنوات بالأسفل.',
    'contact.form.name': 'الاسم الكامل',
    'contact.form.email': 'البريد الإلكتروني',
    'contact.form.phone': 'رقم الهاتف',
    'contact.form.service': 'الخدمة المطلوبة',
    'contact.form.service.placeholder': 'اختر خدمة',
    'contact.form.message': 'الرسالة',
    'contact.form.message.placeholder': 'أخبرنا عن سيارتك والمشكلة...',
    'contact.form.submit': 'إرسال الرسالة',
    'contact.form.success': 'تم إرسال الرسالة بنجاح! سنتواصل معك قريباً.',
    'contact.info.title': 'تواصل سريع',
    'contact.info.address': 'القطاع 4 شارع 19/18، المدينة الصناعية الإمارات، الشارقة، الإمارات',
    'contact.info.hours': 'السبت–الخميس: 8:00 صباحاً – 9:00 مساءً',
    'contact.info.hours.friday': 'الجمعة: 2:00 مساءً – 9:00 مساءً',
    'contact.info.hours.recovery': 'الاستعادة: 24/7',
    'contact.info.follow': 'تابعنا',

    // Booking
    'booking.title': 'حجز موعد',
    'booking.name': 'اسمك',
    'booking.phone': 'رقم الهاتف',
    'booking.email': 'البريد الإلكتروني',
    'booking.car': 'ماركة وموديل السيارة',
    'booking.car.placeholder': 'مثال: تويوتا لاند كرويزر 2023',
    'booking.service': 'نوع الخدمة',
    'booking.service.placeholder': 'اختر الخدمة',
    'booking.date': 'التاريخ المفضل',
    'booking.time': 'الوقت المفضل',
    'booking.time.placeholder': 'اختر الوقت',
    'booking.notes': 'ملاحظات إضافية',
    'booking.notes.placeholder': 'اصف المشكلة أو الخدمة المطلوبة...',
    'booking.submit': 'تأكيد الحجز',
    'booking.success': 'تم تأكيد الحجز! سنتواصل معك قريباً.',

    // Footer
    'footer.desc': 'ورشة سيارات موثوقة في الشارقة. إصلاحات خبيرة للسيارات الخليجية والأمريكية والألمانية والآسيوية. جودة عمل وأسعار شفافة وخدمة استعادة على مدار الساعة.',
    'footer.quicklinks': 'روابط سريعة',
    'footer.services': 'الخدمات',
    'footer.contact': 'اتصل بنا',
    'footer.rights': 'جميع الحقوق محفوظة.',
    'footer.privacy': 'سياسة الخصوصية',
    'footer.terms': 'شروط الخدمة',
  }
};

export const useLanguageStore = create<LanguageState>((set, get) => ({
  lang: 'en',
  dir: 'ltr',
  setLang: (lang) => set({ lang, dir: lang === 'ar' ? 'rtl' : 'ltr' }),
  t: (key: string) => {
    const { lang } = get();
    return translations[lang]?.[key] || key;
  },
}));